// Objective-C API for talking to libhysteria Go package.
//   gobind -lang=objc libhysteria
//
// File is generated by gobind. Do not edit.

#ifndef __Libhysteria_H__
#define __Libhysteria_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class LibhysteriaClientBridge;
@class LibhysteriaJSONConfig;

@interface LibhysteriaClientBridge : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Close 优先关闭 tunDevice，然后关闭 Hysteria 客户端
 */
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
/**
 * ReadToTun 从 tunDev.outChan 拉一个下行 IP 包，返回给 iOS TUN
 */
- (BOOL)readToTun:(NSData* _Nullable)out_ ret0_:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
/**
 * WriteFromTun 将“来自 iOS TUN 的 IP 包”写给 lwIP
 */
- (BOOL)writeFromTun:(NSData* _Nullable)pkt error:(NSError* _Nullable* _Nullable)error;
@end

@interface LibhysteriaJSONConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull server;
@property (nonatomic) NSString* _Nonnull auth;
@property (nonatomic) NSString* _Nonnull psk;
@property (nonatomic) BOOL fastOpen;
@end

FOUNDATION_EXPORT void LibhysteriaStop(void);

#endif
