
// Objective-C API for talking to the following Go packages
//
//	libhysteria
//
// File is generated by gomobile bind. Do not edit.
#ifndef __HysteriaKit_FRAMEWORK_H__
#define __HysteriaKit_FRAMEWORK_H__

#include "Libhysteria.objc.h"
#include "Universe.objc.h"

#endif
