// Objective-C API for talking to libhysteria Go package.
//   gobind -lang=objc libhysteria
//
// File is generated by gobind. Do not edit.

#ifndef __Libhysteria_H__
#define __Libhysteria_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class LibhysteriaAPI;
@class LibhysteriaClientBridge;
@class LibhysteriaInboundUDPPacket;
@class LibhysteriaJSONBandwidthConfig;
@class LibhysteriaJSONConfig;
@class LibhysteriaJSONTLSConfig;
@class LibhysteriaJSONTunConfig;

@interface LibhysteriaAPI : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
- (NSString* _Nonnull)getState;
- (NSString* _Nonnull)pollLogs;
- (NSData* _Nullable)readTunPacket:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)readTunPacketNonBlock:(NSError* _Nullable* _Nullable)error;
- (BOOL)start:(NSString* _Nullable)jsonCfg error:(NSError* _Nullable* _Nullable)error;
- (void)stop;
- (BOOL)writeTunPacket:(NSData* _Nullable)pkt error:(NSError* _Nullable* _Nullable)error;
@end

@interface LibhysteriaClientBridge : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
/**
 * ==================== MODIFICATION START (CRITICAL FIX) ====================
MARK: - CORRECTED (Robust connection with self-cleanup on failure)
 */
- (void)connect;
- (NSString* _Nonnull)getState;
- (BOOL)readToTun:(NSData* _Nullable)out_ ret0_:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (BOOL)writeFromTun:(NSData* _Nullable)p0 error:(NSError* _Nullable* _Nullable)error;
@end

@interface LibhysteriaInboundUDPPacket : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSData* _Nullable data;
// skipped field InboundUDPPacket.SrcAddr with unsupported type: *net.UDPAddr

@end

@interface LibhysteriaJSONBandwidthConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull up;
@property (nonatomic) NSString* _Nonnull down;
@end

@interface LibhysteriaJSONConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull server;
@property (nonatomic) NSString* _Nonnull auth;
// skipped field JSONConfig.TLS with unsupported type: libhysteria.JSONTLSConfig

// skipped field JSONConfig.Bandwidth with unsupported type: libhysteria.JSONBandwidthConfig

// skipped field JSONConfig.Tun with unsupported type: libhysteria.JSONTunConfig

@property (nonatomic) NSString* _Nonnull psk;
@property (nonatomic) BOOL fastOpen;
@property (nonatomic) NSString* _Nonnull alpn;
@end

@interface LibhysteriaJSONTLSConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull sni;
@end

@interface LibhysteriaJSONTunConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull name;
@property (nonatomic) long mtu;
// skipped field JSONTunConfig.Address with unsupported type: []string

// skipped field JSONTunConfig.Route with unsupported type: []string

// skipped field JSONTunConfig.IPv4Exclude with unsupported type: []string

@end

@interface Libhysteria : NSObject
+ (NSError* _Nullable) errNoData;
+ (void) setErrNoData:(NSError* _Nullable)v;

@end

FOUNDATION_EXPORT LibhysteriaAPI* _Nullable LibhysteriaNewAPI(void);

#endif
